language: java
jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2
  
# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/ldtp

branches:
  only: 
    - master
    - feature/DESKTOPAPP-207-ltdpToTravis

stages:
  - release

install: travis_retry mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - stage: release
      name: "Push to Nexus"
      if:
        fork = false AND branch = feature/DESKTOPAPP-207-ltdpToTravis and type != pull_request
      before_install:
        - "cp .travis.settings.xml $HOME/.m2/settings.xml"
      script:
        # Use full history for release
        - git checkout -B "${TRAVIS_BRANCH}"
        - git status
        # Add email to link commits to user
        - git config user.email "${GIT_EMAIL}"
        # Skip building of release commits
        - mvn -X --batch-mode -q -DscmCommentPrefix="[maven-release-plugin][skip ci] " -Dusername="${GIT_USERNAME}" -Dpassword="${GIT_PASSWORD}" -DskipTests -Darguments=-DskipTests -DreleaseVersion=desktopapp-207-2 -DdevelopmentVersion=0.0.2-SNAPSHOT release:clean release:prepare release:perform
