language: java
jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2
  
# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/ldtp

branches:
  only: 
    - master
    - /feature\/.*/
    - /fix\/.*/

stages:
  - build
  - deploy

before_install: "cp .travis.settings.xml $HOME/.m2/settings.xml"
install: travis_retry mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    - name: "Build"
      stage: build
      script:
        - echo "The tests are skipped as it requires different OS settings"

    - name: "Deploy snapshot on nexus"
      stage: deploy
      if: fork = false AND branch = fix/DESKTOPAPP-171-version and type != pull_request
      script:
        - mvn --batch-mode -U clean deploy -DskipTests
