language: java
jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2
  
# the cache can grow constantly
before_cache:
  - rm -rf $HOME/.m2/repository/org/alfresco/ldtp

branches:
  only: 
    - master
    - /feature\/.*/
    - /fix\/.*/
import:
  - source: Alfresco/alfresco-build-tools:.travis.java.yml@v1.1.5

stages:
  - build
  - deploy

#before_install: "cp settings.xml $HOME/.m2/settings.xml"
install: travis_retry mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jobs:
  include:
    #- name: "Build"
    #  stage: build
     # script:
       # - echo "The tests are skipped as it requires different OS settings"

    - name: "Deploy snapshot on nexus"
      stage: deploy
      if: fork = false AND branch = master and type != pull_request
      script:
        - mvn --batch-mode -U clean deploy -DskipTests
